name: Fabs.io
favicon: null
layout_spectrum: 0.967512822477147
typography_spectrum: 0.34467889042571187
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8d8d8'
    - '#0e0e0e'
    - '#2b2b2b'
    - '#898989'
    - '#a7a7a7'
  brandStrength: 1
  lightness: 0.6621929726097733
  saturation: 0.21435026708059013
  rhythmicContrast: 0.8232980859465897
purpose: []
